# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 14:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[aA-zZ]+\\Z$', code='invalid', message='Enter a valid first name.')], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[aA-zZ]+$', code='invalid', message='Enter a valid last name.')], verbose_name='Last Name')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('[aA-zZ]+(?:[aA-zZ]+) [aA-zZ]+\\Z', code='invalid', message='Enter a valid name (first & last, letters only).')], verbose_name='Full Name')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z', 32), code='invalid', message='Enter a valid phone number (Only Integers).')], verbose_name='Phone Number')),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(code='invalid', message='Enter a valid email.')], verbose_name='Email Address')),
                ('comment', models.TextField(validators=[django.core.validators.MinLengthValidator(4, message='Type at least 1 word (4 characters)')], verbose_name='Comment')),
                ('status', models.CharField(choices=[('r', 'Responded'), ('c', 'Closed'), ('n', 'New')], default='n', max_length=1)),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Admin Notes')),
                ('remote_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Remote IP')),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
    ]
